#JDBC Configuration for Database Connection
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://vprofile-actions.ctc80uemwlo0.ap-south-1.rds.amazonaws.com:3306/accounts?useSSL=true&serverTimezone=UTC
jdbc.username=admin
jdbc.password=LNmbPYR7U03ebom1QpI0

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=${MEMCACHED_HOST:mc01}
memcached.active.port=${MEMCACHED_PORT:11211}
#For StandBy Host
memcached.standBy.host=${MEMCACHED_STANDBY_HOST:mc02}
memcached.standBy.port=${MEMCACHED_STANDBY_PORT:11211}

#RabbitMQ Configuration
rabbitmq.address=${RABBITMQ_HOST:rmq01}
rabbitmq.port=${RABBITMQ_PORT:5672}
rabbitmq.username=${RABBITMQ_USER:rabbit}
rabbitmq.password=${RABBITMQ_PASSWORD:rabbit123}

#Elasticsearch Configuration
elasticsearch.host=${ES_HOST:es01}
elasticsearch.port=${ES_PORT:9300}
elasticsearch.cluster=${ES_CLUSTER:vprofile}
elasticsearch.node=${ES_NODE:vprofile-node}
