name: Hprofile Actions
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Workflow
        run: echo "Workflow Works!"
